schema:
  order_id:
    type: integer
    min: 1000
    max: 9999
  symbol:
    type: string
    values: ["AAPL", "GOOGL", "MSFT", "TSLA"]
  order_type:
    type: string
    values: ["market", "limit", "stop"]
  quantity:
    type: integer
    min: 1
    max: 100
  price:
    type: float
    min: 100.0
    max: 1500.0
  timestamp:
    type: datetime
    format: "%Y-%m-%d %H:%M:%S"

generator:
  frequency: 1
  destination:
    type: kafka
    kafka_bootstrap_servers: "localhost:9092"
    topic: "orders"