FROM python:3.12-slim

WORKDIR /app

COPY /lib/requirements.txt .

RUN pip install -r requirements.txt

COPY faker/main.py .
COPY faker/config.yaml .
COPY lib/SchemaBuilder.py .
COPY lib/MessageGenerator.py .
COPY lib/ConfigLoader.py .

CMD ["python", "main.py"]

#CMD ["ls", "-la"]
